[env]
# ⚠️ need to be visible for the esp32 connection
TOBOGGAN_HOST = "0.0.0.0"

[tools]
"cargo:bacon" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:svgo" = "latest"

[tasks.build]
description = "Build the riir.toml file"
run = "toboggan build -p ./slides -o riir.toml && toboggan build -p ./slides -o index.html"

[tasks.dev]
description = "Serve and watch the presentation"
run = "RUST_LOG=info toboggan serve -p ./riir.toml --public-dir ./public/ --watch"

[tasks.run]
description = "Serve the presentation"
run = "RUST_LOG=warn toboggan serve -p ./riir.toml --public-dir ./public/"
